#!/usr/bin/env python3
"""
Fetch GET /api/schemas and write the fields of the entities this agent
depends on into docs/ENTITY_MAP.md, so data-model.md and
contracts/platform-surface.md can be corrected against the live schema
instead of the gap_report.md guesses they started from (tasks.md T008/T009).

Usage:
  python scripts/snapshot_schemas.py --instance suryodaya
  python scripts/snapshot_schemas.py --instance keystone

Requires network access and valid .env credentials; this cannot run in
a sandboxed/offline environment, which is why its output is checked in
to docs/ENTITY_MAP.md rather than regenerated on every run.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agent.mcp_client import create_client_for  # noqa: E402

ENTITIES_OF_INTEREST = [
    "Project",
    "Task",
    "Milestone",
    "ProjectResourceAllocation",
    "ProjectResourceProfile",
    "CalendarEvent",
    "Timesheet",
    "AgentMemory",
]


def format_entity_section(name: str, schema: dict) -> str:
    fields = schema.get("properties", schema.get("fields", {}))
    required = schema.get("required", [])
    lines = [f"### {name}", ""]
    if not fields:
        lines.append("_No fields found in GET /api/schemas for this entity._")
        lines.append("")
        return "\n".join(lines)
    lines.append("| Field | Type | Required |")
    lines.append("|---|---|---|")
    for field_name, field_def in fields.items():
        field_type = field_def.get("type", "unknown") if isinstance(field_def, dict) else "unknown"
        is_required = "yes" if field_name in required else ""
        lines.append(f"| `{field_name}` | {field_type} | {is_required} |")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--instance", default="suryodaya", choices=["suryodaya", "keystone"])
    parser.add_argument("--out", default=str(ROOT / "docs" / "ENTITY_MAP.md"))
    args = parser.parse_args()

    client = create_client_for(args.instance)
    schemas = client.get_schemas()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    sections = [f"# Entity Map ({args.instance})\n",
                "Generated by `scripts/snapshot_schemas.py`. Correct `data-model.md` and "
                "`contracts/platform-surface.md` against this, not the other way around.\n"]
    for entity in ENTITIES_OF_INTEREST:
        schema = schemas.get(entity) or schemas.get(entity.lower()) or {}
        sections.append(format_entity_section(entity, schema))

    out_path.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {out_path}")

    raw_path = out_path.with_suffix(".raw.json")
    raw_path.write_text(json.dumps(schemas, indent=2), encoding="utf-8")
    print(f"Wrote raw schema dump to {raw_path}")


if __name__ == "__main__":
    main()
